### PR TITLE
fix tests

### PR DESCRIPTION
**Pull request by lukechilds**
Changed to inline comment as requested in https://github.com/sindresorhus/get-stdin/pull/15

### CODE REVIEW

**Comment by SamVerschueren** [comment]
It's best practice to disable specific rules instead of the entire line. This could potentially hide other errors.

```
// eslint-disable-line xo/no-process-exit
```

**Comment by lukechilds** [comment]
Cool, don't close I'll force push 👍

**Comment by SamVerschueren** [comment]
While you're at it. Could you change `5` to `6` in `.travis.yml`?

```yaml
sudo: false
language: node_js
node_js:
  - '6'
  - '4'
  - '0.12'
```

**Comment by lukechilds** [comment]
Now you tell me... 😆

**Comment by SamVerschueren** [comment]
Hehe, sorry :D

**Comment by lukechilds** [comment]
@SamVerschueren Done.

Do you specifically want version 6? Are you aware you can set the version as `node` and it'll use the latest available version of node?

**Comment by SamVerschueren** [comment]
No specifically 6. It will become LTS in October and should be tested as long as it is maintained.

**Comment by lukechilds** [comment]
Cool, just checking 😉

**Comment by SamVerschueren** [comment]
Thanks @lukechilds :beers:

**Pull request merged**
