### PR TITLE
feat: add default export

### PR DESCRIPTION
**Pull request by KnisterPeter**
add es6 modules support

### CODE REVIEW

**Comment by sindresorhus** [comment]
No thanks. This is not the way to fix it.

**Comment by KnisterPeter** [comment]
Whats the way you like it?

**Comment by sindresorhus** [comment]
The fix belongs in your code. You should require all the modules you use to change.

**Comment by KnisterPeter** [comment]
This (https://github.com/KnisterPeter/react-to-typescript-definitions/blob/master/src/index.ts#L3) is my code. It does not look that handy in typescript. Thats the problem if the user of `get-stdin` uses es6 modules. The `modules.exports` namespaces it not available.

**Comment by SamVerschueren** [comment]
Change your `get-stdin` typings to this

```ts
declare module 'get-stdin' {
  function getStdin(): PromiseLike<string>;
  namespace getStdin { }
  export = getStdin;
}
```

```ts
import * as getStdin from 'get-stdin';

getStdin().then(result => {
    console.log(result);
});
```

**Comment by KnisterPeter** [comment]
Thanks. You are right.
Its not that 'es6 like'. But thats good enough for me.

**Comment by KnisterPeter** [comment]
Hi @sindresorhus, @SamVerschueren,

if you don't mind I would like to rediscuss this PR.

The solution given by @SamVerschueren does work but it does not feel right.  
After reading [this article](https://stackoverflow.com/questions/39415661/why-cant-i-import-a-class-or-function-with-import-as-x-from-y?answertab=votes#tab-top) about how to write typings (okay I know you don't care about typescript which is okay) I now know why it doesn't feel right.

The ES2015 module namespace is not callable and cannot called with new as [per spec](http://www.ecma-international.org/ecma-262/6.0/#sec-module-namespace-exotic-objects) as it is not extensibel and may only contain key-value pairs.
That means importing it by using `import * as ns from 'module';` will break if there are native ES2015 implementations.  
In contrast to this my proposed change will keep the current nodish behaviour by still exporting `module.exports =` as well as make it ES2015 ready by exporting a default as well.

If you don't like to rediscuss this just keep it closed.

**Comment by SamVerschueren** [comment]
@KnisterPeter I use TypeScript as well (Angular 2) so I do kinda care. But I don't believe that module authors should change code to get it to work on systems it's not designed for (in this case ES2015 modules). I agree that the `namespace` hack is not ideally. I read the article as well after I posted this answer and I wouldn't suggest it anymore. As per the article you linked, if you want to include CommonJS modules, you should do `import getStdin = require('get-stdin');`.  This **is** a CommonJS module, exporting a `default` doesn't change that and doesn't make it a ES2015 module. So I'd suggest using the `import-require` method to do this.

**Comment by KnisterPeter** [comment]
Yes, I would use the `import-require` from now on if I use common-js modules which are not usable as es2015 modules.
But I would favor that software is usable either as common-js or as es2015 module. There may be js runtimes which run on the server (or other environments) which only support es2015 and not common-js which are not node.

But its your code and your decision. :smile:

**Pull request closed without merging**
