### PR TITLE
Read data asynchronously

### PR DESCRIPTION
**Pull request by lukechilds**
Doesn't block while waiting for stdin to finish.

Discussed in https://github.com/sindresorhus/get-stdin/issues/13

### CODE REVIEW

**Comment by SamVerschueren** [comment]
Could you rebase from master?

**Comment by lukechilds** [comment]
Am doing, gimme a second jeez.

**Comment by lukechilds** [comment]
Sorted 😉

**Comment by SamVerschueren** [comment]
Sorry, didn't want to put pressure on you :).

**Comment by lukechilds** [comment]
Haha, no worries man I was just kidding.

**Comment by kevva** [comment]
It's already async, and this code is intentional. See https://github.com/sindresorhus/get-stdin/commit/eedcea465240ea0cf68f822ea4b5d2420526dc4a.

**Comment by lukechilds** [comment]
Are you sure? Does `while (chunk = stdin.read())` not block?

**Comment by lukechilds** [comment]
> When get-stdin subscribe to stdin, it blocks the process until something is written to stdin.

https://github.com/sindresorhus/get-stdin/issues/13#issuecomment-224056984

**Comment by lukechilds** [comment]
@SamVerschueren @kevva I just had another look at this and it is indeed currently async.

The difference is with the `readable` event (introduced in Streams2) you can choose whether to read the data now or later. With `data` you have to handle the data in the callback or you lose it forever. The current code uses the more advanced `readable` event but always handles the data straight away anyway.

In effect it's kind of using the new Streams2 api `readable` event to emulate the behaviour of old `data` event. Although they should both have the same behaviour I think it makes more sense to merge this PR and revert back to `data`. It's much more readable, and more clearly shows the intentions of this code, as demonstrated by the confusion in this PR and the related issue. 😆 

Up to you guys :)

**Comment by sindresorhus** [comment]
I guess, but I don't want to take the chance. Not worth potential breakage. Too many modules depend on this one. The current version should also be slightly faster as event emitting is slower than reading from a function, and this version uses a lot less events.

**Pull request closed without merging**
